# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentsApp', '0004_studentinfo_full_name'),
        ('coursesApp', '0008_course_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizFile', models.FileField(upload_to='')),
                ('deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursesApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsApp.StudentInfo')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='studentsCompleted',
            field=models.ManyToManyField(to='quizesApp.QuizComplete'),
        ),
    ]
