# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizFile',
            field=models.FileField(upload_to='quizes/%Y/%m/%d/%H/%M/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='studentsCompleted',
            field=models.ManyToManyField(blank=True, to='quizesApp.QuizComplete'),
        ),
    ]
