# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionManagerApp', '0001_initial'),
        ('quizesApp', '0002_auto_20171122_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='session',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='sessionManagerApp.Session'),
            preserve_default=False,
        ),
    ]
