# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizesApp', '0003_auto_20171124_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_grade',
            field=models.IntegerField(default=10),
        ),
    ]
