# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizesApp', '0004_quiz_max_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcomplete',
            name='answerFile',
            field=models.FileField(default=None, upload_to='quizes/%Y/%m/%d/%H/%M/'),
            preserve_default=False,
        ),
    ]
