# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizesApp', '0005_quizcomplete_answerfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcomplete',
            name='answerFile',
            field=models.FileField(upload_to='answers/%Y/%m/%d/%H/%M/'),
        ),
        migrations.AlterField(
            model_name='quizcomplete',
            name='grade',
            field=models.CharField(default='???', max_length=10),
        ),
    ]
