# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='chatActive',
            field=models.BooleanField(default=False),
        ),
    ]
