# Generated by Django 2.0.2 on 2018-02-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionManagerApp', '0002_session_chatactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFullName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionManagerApp.Session')),
            ],
        ),
    ]
