# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_auto_20171114_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersemester',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsApp.StudentInfo'),
        ),
    ]
