# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('info', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=100)),
                ('usersGoing', models.ManyToManyField(blank=True, related_name='users_attending', to=settings.AUTH_USER_MODEL)),
                ('usersInterested', models.ManyToManyField(blank=True, related_name='users_thinking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
