# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 13, 21, 14, 284805, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
