# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='applications_duration',
            field=models.TimeField(default='02:00:00'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.TimeField(default='02:00:00'),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_app_result',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_oral_result',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_written_result',
            field=models.IntegerField(default=140),
        ),
    ]
