# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsApp', '__first__'),
        ('coursesApp', '0005_auto_20171116_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departmentsApp.Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
