# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesApp', '0006_auto_20171117_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
    ]
