# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='prequel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departmentsApp.Group'),
        ),
        migrations.AddField(
            model_name='department',
            name='sequels',
            field=models.ManyToManyField(related_name='group_sequels', to='departmentsApp.Group'),
        ),
    ]
