# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsApp', '0004_auto_20171118_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
