# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsApp', '0005_auto_20171118_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='prequel',
        ),
    ]
