# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsApp', '0006_remove_department_prequel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dep_name',
        ),
        migrations.AddField(
            model_name='department',
            name='prequel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='departmentsApp.Group'),
        ),
    ]
