# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmentsApp', '0007_auto_20171118_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='prequel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='departmentsApp.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
