# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canChangeSessions', models.BooleanField(default=False)),
                ('minHoursWeek', models.IntegerField(default=10)),
                ('maxHoursWeek', models.IntegerField(default=10)),
            ],
        ),
    ]
