# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='maxStudentYear',
            field=models.IntegerField(default=4),
        ),
    ]
