# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0003_auto_20171114_1019'),
        ('sessionManagerApp', '0002_delete_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
